### ISSUE TITLE
프론트 앞으로 진행할 작업 이슈화하기

### ISSUE THREAD

**Issue by charlieppark** [Receipt-Information-Parser/Frontend#1]

**Comment by JWseop** [comment]
전체일정
UI 코딩 -> 백 연결

UI 코딩
 - 피그마 짜기 (디자인, 유저플로우O) (3/25 토)
 - 코드 스타일 정하기(3/26 일)
 - 화면 분담(피그마 기준)(3/26 일 현찬이 알바끝나고 21시 이후)
 - 로컬 테스트 (디버깅)
